"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

load_dotenv()  # Reads the .env file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

 copilot/sub-pr-1-again
# Helper constants
# Environment variables are normalized to lowercase before comparison
TRUTHY_ENV_VALUES = {'1', 'true', 't', 'yes', 'y', 'on'}

# --- SECURITY SETTINGS ---
# DEBUG: Accept common truthy values
DEBUG = os.environ.get('DEBUG', '').strip().lower() in TRUTHY_ENV_VALUES

# SECRET_KEY: Fail fast with clear error if missing, or use dev-only default
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Development-only fallback
        SECRET_KEY = 'django-insecure-dev-key-change-this-in-production'
    else:
        raise ImproperlyConfigured(
            'SECRET_KEY environment variable is required. '
            'Set it in your .env file or environment.'
        )

# ALLOWED_HOSTS: Load from environment with proper security defaults
allowed_hosts_env = os.environ.get('ALLOWED_HOSTS')
if allowed_hosts_env:
    ALLOWED_HOSTS = [
        host.strip()
        for host in allowed_hosts_env.split(',')
        if host.strip()
    ]
elif DEBUG:
    # In development, default to allowing all hosts
    ALLOWED_HOSTS = ['*']
else:
    # In production, require ALLOWED_HOSTS to be explicitly set
    raise ImproperlyConfigured(
        'ALLOWED_HOSTS environment variable is required in production. '
        'Set it to a comma-separated list of allowed hosts in your .env file or environment.'
    )

# This ensures DEBUG is True only if .env says so
DEBUG = os.environ.get('DEBUG') == 'True'

# --- REPLACE YOUR SECURITY SECTION WITH THIS ---
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:  # Catches both None and empty string
    if DEBUG:
        # Development-only fallback - NEVER use this in production
        SECRET_KEY = 'django-insecure-dev-key-do-not-use-in-production'
    else:
        raise ImproperlyConfigured(
            'SECRET_KEY environment variable is not set. '
            'Please set SECRET_KEY in your environment or .env file.'
        )

ALLOWED_HOSTS = ['*'] 
 feature/core-setup
# -----------------------------------------------

INSTALLED_APPS = [
    'accounts',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


# Database configuration with proper fallback
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{(BASE_DIR / "db.sqlite3").as_posix()}',
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'accounts.CustomUser'